# Generated by Django 3.0.5 on 2022-12-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20221202_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
