# Generated by Django 3.0.5 on 2022-12-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
