# Generated by Django 3.0.5 on 2022-12-12 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20221211_2150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pictures',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='picture',
            new_name='image',
        ),
    ]
